import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// Helper to draw clean header on documents
const drawHeader = (doc, title) => {
  // Brand Header banner (navy primary color #1A3C5E)
  doc.setFillColor(26, 60, 94);
  doc.rect(0, 0, 210, 40, "F");

  // Logo text or icon
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("CROWN ASSURANCE", 15, 24);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("InsureSpace — Premium Insurance Platform", 15, 32);

  // Document Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), 140, 26, { align: "left" });

  // Draw thin gold-like/accent separator line (accent color #0FA89E)
  doc.setDrawColor(15, 168, 158);
  doc.setLineWidth(2);
  doc.line(0, 40, 210, 40);
};

// Helper to draw clean footer
const drawFooter = (doc, pageNum) => {
  const pageHeight = doc.internal.pageSize.height;
  
  // Thin footer border line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(15, pageHeight - 20, 195, pageHeight - 20);

  // Footer text
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by InsureSpace Portal. Secure Client-side PDF Service.", 15, pageHeight - 12);
  doc.text(`Page ${pageNum || 1}`, 185, pageHeight - 12);
};

// Helper to draw status badge
const drawStatusBadge = (doc, x, y, statusText, isActive) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  
  const textWidth = doc.getTextWidth(statusText);
  const badgeWidth = textWidth + 12;
  const badgeHeight = 6;
  
  // Fill badge background: Green for active/success/approved, Red/Gold for deactivated/pending
  if (isActive) {
    doc.setFillColor(16, 185, 129); // soft green background or solid
    doc.setDrawColor(16, 185, 129);
    doc.setTextColor(16, 185, 129);
  } else {
    doc.setFillColor(239, 68, 68); // soft red
    doc.setDrawColor(239, 68, 68);
    doc.setTextColor(239, 68, 68);
  }
  
  // Custom transparent-like badge drawing
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(x, y - 4.5, badgeWidth, badgeHeight, 1.5, 1.5, "FD");
  doc.text(statusText, x + 6, y);
};// 1. Generate Individual User/Agent Profile PDF
export const generateUserPDF = (user) => {
  const doc = new jsPDF();

  drawHeader(doc, `${user.role} profile`);

  // Main Card container border
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(15, 55, 180, 120, 3, 3, "FD");

  // Vertical Navy accent bar on the left edge of the card
  doc.setFillColor(26, 60, 94);
  doc.rect(15, 55, 3, 120, "F");

  // Subtitle header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(26, 60, 94);
  doc.text("Account & Security Credentials", 25, 70);

  // Decorative blue line
  doc.setDrawColor(37, 99, 168);
  doc.setLineWidth(1.5);
  doc.line(25, 75, 60, 75);

  // Detail Fields using jsPDF-autotable for premium layout
  const rows = [
    ["System User ID", String(user.id)],
    ["Full Legal Name", user.fullName],
    ["Email Address", user.email],
    ["Phone Number", user.phoneNumber || "N/A"],
    ["Assigned System Role", user.role],
    ["Account Status", user.active ? "ACTIVE" : "DEACTIVATED"]
  ];

  autoTable(doc, {
    startY: 85,
    margin: { left: 25, right: 25 },
    theme: "plain",
    body: rows,
    columnStyles: {
      0: { cellWidth: 50, fontStyle: "bold", textColor: [100, 116, 139], fontSize: 11 },
      1: { fontStyle: "bold", fontSize: 11, textColor: [15, 23, 42] }
    },
    didDrawCell: (data) => {
      // Draw a custom status badge for the status field
      if (data.column.index === 1 && data.row.index === 5) {
        doc.setFillColor(255, 255, 255);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 2, data.cell.y + 4.5, data.cell.text[0], user.active);
      }
    },
    styles: {
      minCellHeight: 10,
      valign: "middle"
    }
  });

  // Disclaimer / Footer area in the card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Note: This document contains system configuration and access rights details.", 25, 165);

  drawFooter(doc, 1);

  doc.save(`profile_${user.fullName.toLowerCase().replace(/\s+/g, "_")}.pdf`);
};

// 2. Generate Bulk Users List PDF
export const generateUserListPDF = (users, filters) => {
  const doc = new jsPDF();
  drawHeader(doc, "User Registry Directory");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(26, 60, 94);
  doc.text("System Directory Summary", 15, 52);

  // Active filters info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Active Filters: Role = ${filters.role || "ALL"}, Status = ${filters.status || "ALL"}`, 15, 58);
  doc.text(`Total Records Extracted: ${users.length}`, 155, 58);

  const tableHeaders = [["ID", "Full Name", "Email Address", "Phone Number", "Role", "Status"]];
  const tableData = users.map(u => [
    u.id,
    u.fullName,
    u.email,
    u.phoneNumber || "N/A",
    u.role,
    u.active ? "Active" : "Deactivated"
  ]);

  autoTable(doc, {
    startY: 65,
    head: tableHeaders,
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [26, 60, 94],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10
    },
    styles: {
      fontSize: 9,
      cellPadding: 4
    },
    columnStyles: {
      0: { cellWidth: 12 },
      4: { fontStyle: "bold" },
      5: { fontStyle: "bold" }
    },
    didDrawCell: (data) => {
      // Draw badge in Status column
      if (data.column.index === 5 && data.cell.section === "body") {
        const text = data.cell.text[0];
        const isActive = text === "Active";
        // Clear background
        doc.setFillColor(data.row.index % 2 === 0 ? 255 : 245, 245, 245);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 4, data.cell.y + 4.5, text, isActive);
      }
    }
  });

  drawFooter(doc, 1);
  doc.save(`user_directory_report.pdf`);
};

// 3. Generate Individual Payslip / Payment Receipt PDF
export const generatePaymentPDF = (txn, formattedDate, formattedTime) => {
  const doc = new jsPDF();
  drawHeader(doc, "Payment Receipt (Payslip)");

  // Left Column: Payment Summary
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  // Receipt container card
  doc.roundedRect(15, 50, 180, 140, 2, 2, "FD");

  // Vertical Navy accent bar on the left edge of the card
  doc.setFillColor(26, 60, 94);
  doc.rect(15, 50, 3, 140, "F");

  // Receipt details header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(26, 60, 94);
  doc.text("Receipt Voucher Details", 25, 66);
  
  doc.setDrawColor(37, 99, 168);
  doc.setLineWidth(1.5);
  doc.line(25, 71, 60, 71);

  const rows = [
    ["Transaction Reference", txn.transactionReference],
    ["Policy Number Reference", txn.policyNumber],
    ["Date of Payment", `${formattedDate} at ${formattedTime}`],
    ["Mode of Payment", txn.paymentMode],
    ["Amount Settled", `INR ${txn.amount.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`],
    ["Payment Status", "SUCCESS (VERIFIED)"]
  ];

  autoTable(doc, {
    startY: 80,
    margin: { left: 25, right: 25 },
    theme: "plain",
    body: rows,
    columnStyles: {
      0: { cellWidth: 55, fontStyle: "bold", textColor: [100, 116, 139], fontSize: 11 },
      1: { fontStyle: "bold", fontSize: 11, textColor: [15, 23, 42] }
    },
    didDrawCell: (data) => {
      // Draw status badge
      if (data.column.index === 1 && data.row.index === 5) {
        doc.setFillColor(255, 255, 255);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 2, data.cell.y + 4.5, "SUCCESSFUL", true);
      }
    },
    styles: {
      minCellHeight: 11,
      valign: "middle"
    }
  });

  // Thank you message
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 168, 158); // Accent color
  doc.text("Thank you for your premium payment!", 25, 162);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("This receipt is automatically generated and does not require a physical signature.", 25, 168);
  doc.text("For any queries, please reach support at support@crownassurance.com.", 25, 173);

  // Digital Signature Box
  doc.setDrawColor(26, 60, 94);
  doc.rect(145, 145, 40, 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(26, 60, 94);
  doc.text("VERIFIED BY", 149, 150);
  doc.setFont("helvetica", "italic");
  doc.text("Crown Assurance Group", 149, 155);
  doc.text("Audit Server", 149, 160);

  drawFooter(doc, 1);
  doc.save(`receipt_${txn.transactionReference}.pdf`);
};

// 4. Generate Individual Claim Slip PDF
export const generateClaimPDF = (claim, claimNum) => {
  const doc = new jsPDF();
  drawHeader(doc, "Claim Slip Voucher");

  // Main Card container border
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(15, 50, 180, 165, 2, 2, "FD");

  // Vertical Navy accent bar on the left edge of the card
  doc.setFillColor(26, 60, 94);
  doc.rect(15, 50, 3, 165, "F");

  // Claim details header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(26, 60, 94);
  doc.text("Insurance Claim Summary", 25, 66);
  
  doc.setDrawColor(37, 99, 168);
  doc.setLineWidth(1.5);
  doc.line(25, 71, 60, 71);

  const status = (claim.claimStatus || 'SUBMITTED').toUpperCase();
  const isApproved = status === "APPROVED" || status === "RECOMMENDED" || status === "SUCCESS" || status === "ACTIVE";

  const rows = [
    ["Claim Reference Number", claimNum],
    ["Associated Policy No.", claim.policyNumber || "N/A"],
    ["Incident Date Reported", claim.incidentDate || "N/A"],
    ["Claim Description / Reason", claim.claimReason || "No reason provided"],
    ["Total Amount Claimed", `INR ${(claim.claimAmount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`],
    ["Claim Settlement Status", status],
    ["Agent Audit Remarks", claim.agentRemarks === "null" || !claim.agentRemarks ? "Awaiting review" : claim.agentRemarks],
    ["Admin Decision Remarks", claim.adminRemarks === "null" || !claim.adminRemarks ? "Awaiting decision" : claim.adminRemarks]
  ];

  autoTable(doc, {
    startY: 80,
    margin: { left: 25, right: 25 },
    theme: "plain",
    body: rows,
    columnStyles: {
      0: { cellWidth: 55, fontStyle: "bold", textColor: [100, 116, 139], fontSize: 10.5 },
      1: { fontStyle: "bold", fontSize: 10.5, textColor: [15, 23, 42] }
    },
    didDrawCell: (data) => {
      // Draw status badge
      if (data.column.index === 1 && data.row.index === 5) {
        doc.setFillColor(255, 255, 255);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 2, data.cell.y + 4.5, status, isApproved);
      }
    },
    styles: {
      minCellHeight: 11,
      valign: "middle"
    }
  });

  // Footer notes in the card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Disclaimer: Claims are processed under statutory guidelines. Approvals are subject to verification.", 25, 198);
  doc.text("If any details are incorrect, please contact your assigned agent immediately.", 25, 203);

  // Verification Box
  doc.setDrawColor(26, 60, 94);
  doc.rect(145, 185, 40, 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(26, 60, 94);
  doc.text("AUDITED BY CROWN", 149, 190);
  doc.setFont("helvetica", "normal");
  doc.text(`ID: ${claim.id || "N/A"}`, 149, 195);
  doc.text("Audit Status: Verified", 149, 200);

  drawFooter(doc, 1);
  doc.save(`claim_slip_${claimNum}.pdf`);
};

// 5. Generate Individual Policy PDF
export const generatePolicyPDF = (policy, customerName) => {
  const doc = new jsPDF();
  drawHeader(doc, "Policy Schedule Card");

  // Main Card container border
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(15, 50, 180, 150, 2, 2, "FD");

  // Vertical Navy accent bar on the left edge of the card
  doc.setFillColor(26, 60, 94);
  doc.rect(15, 50, 3, 150, "F");

  // Policy details header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(26, 60, 94);
  doc.text("Insurance Policy Schedule", 25, 66);
  
  doc.setDrawColor(37, 99, 168);
  doc.setLineWidth(1.5);
  doc.line(25, 71, 60, 71);

  const status = (policy.policyStatus || 'PENDING').toUpperCase();
  const isActive = status === 'ACTIVE';

  const rows = [
    ["Policy Reference Number", policy.policyNumber || "N/A"],
    ["Policyholder Name", customerName || "N/A"],
    ["Insurance Product Type", policy.productType || "N/A"],
    ["Insurance Plan Name", policy.planName || "N/A"],
    ["Sum Insured (Coverage Limit)", `INR ${(policy.coverageAmount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`],
    ["Available Coverage Balance", `INR ${(policy.remainingCoverage !== undefined && policy.remainingCoverage !== null ? policy.remainingCoverage : policy.coverageAmount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`],
    ["Premium Installment", `INR ${(policy.premiumAmount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })} / ${policy.premiumType || 'TERM'}`],
    ["Commencement Date", policy.startDate ? new Date(policy.startDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A'],
    ["Policy Status", status]
  ];

  autoTable(doc, {
    startY: 80,
    margin: { left: 25, right: 25 },
    theme: "plain",
    body: rows,
    columnStyles: {
      0: { cellWidth: 55, fontStyle: "bold", textColor: [100, 116, 139], fontSize: 10.5 },
      1: { fontStyle: "bold", fontSize: 10.5, textColor: [15, 23, 42] }
    },
    didDrawCell: (data) => {
      // Draw status badge
      if (data.column.index === 1 && data.row.index === 7) {
        doc.setFillColor(255, 255, 255);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 2, data.cell.y + 4.5, status, isActive);
      }
    },
    styles: {
      minCellHeight: 11,
      valign: "middle"
    }
  });

  // Footer notes in the card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Disclaimer: This policy schedule acts as proof of contract and coverage verification.", 25, 185);
  doc.text("All claims must reference the Policy Number. Contact support for endorsements.", 25, 190);

  // Verification Box
  doc.setDrawColor(26, 60, 94);
  doc.rect(145, 172, 40, 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(26, 60, 94);
  doc.text("CROWN INSURANCE", 148, 177);
  doc.setFont("helvetica", "normal");
  doc.text("Voucher: Schedule", 148, 182);
  doc.text("Status: Authenticated", 148, 187);

  drawFooter(doc, 1);
  doc.save(`policy_schedule_${policy.policyNumber || 'details'}.pdf`);
};

// 6. Generate Individual Customer Details PDF
export const generateCustomerPDF = (c) => {
  const doc = new jsPDF();
  drawHeader(doc, "Customer Profile Receipt");

  // Main Card container border
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(15, 50, 180, 140, 2, 2, "FD");

  // Vertical Navy accent bar on the left edge of the card
  doc.setFillColor(26, 60, 94);
  doc.rect(15, 50, 3, 140, "F");

  // Header inside the card
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(26, 60, 94);
  doc.text("Customer Profile Summary", 25, 66);
  
  doc.setDrawColor(37, 99, 168);
  doc.setLineWidth(1.5);
  doc.line(25, 71, 60, 71);

  const dob = c.dateOfBirth
    ? new Date(c.dateOfBirth).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
    : 'N/A';
  const location = c.city && c.state ? `${c.city}, ${c.state}` : c.city || c.state || 'N/A';
  const nominee = c.nomineeName ? `${c.nomineeName} (${c.nomineeRelation || 'Nominee'})` : 'N/A';

  const rows = [
    ["System Customer ID", String(c.id || "N/A")],
    ["Full Legal Name", c.fullName || "N/A"],
    ["Email Address", c.email || "N/A"],
    ["Phone Number", c.phoneNumber || "N/A"],
    ["Date of Birth", dob],
    ["Residential Location", location],
    ["Assigned Nominee", nominee]
  ];

  autoTable(doc, {
    startY: 80,
    margin: { left: 25, right: 25 },
    theme: "plain",
    body: rows,
    columnStyles: {
      0: { cellWidth: 55, fontStyle: "bold", textColor: [100, 116, 139], fontSize: 10.5 },
      1: { fontStyle: "bold", fontSize: 10.5, textColor: [15, 23, 42] }
    },
    styles: {
      minCellHeight: 11,
      valign: "middle"
    }
  });

  // Footer notes inside card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Note: This summary represents the legal profile record registered under Crown Assurance.", 25, 172);

  // Digital Registry Mark
  doc.setDrawColor(26, 60, 94);
  doc.rect(145, 160, 40, 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(26, 60, 94);
  doc.text("REGISTRY PROFILE", 147, 165);
  doc.setFont("helvetica", "normal");
  doc.text(`UID: ${c.id || "N/A"}`, 147, 170);
  doc.text("Record: Verified", 147, 175);

  drawFooter(doc, 1);
  doc.save(`customer_profile_${(c.fullName || 'details').toLowerCase().replace(/\s+/g, '_')}.pdf`);
};

// 7. Generate Bulk Policies List PDF
export const generatePolicyListPDF = (policies) => {
  const doc = new jsPDF();
  drawHeader(doc, "Policies Registry Directory");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(26, 60, 94);
  doc.text("System Policy Directory Summary", 15, 52);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total Records Extracted: ${policies.length}`, 15, 58);

  const tableHeaders = [["Policy No.", "Plan Name", "Policyholder", "Product Type", "Max Cover", "Available Cover", "Premium", "Start Date", "Status"]];
  const tableData = policies.map(p => [
    p.policyNumber || "N/A",
    p.planName || "Insurance Plan",
    p.customerName || p.customer?.fullName || "N/A",
    p.productType || "N/A",
    `INR ${(p.coverageAmount || 0).toLocaleString("en-IN")}`,
    `INR ${(p.remainingCoverage !== undefined && p.remainingCoverage !== null ? p.remainingCoverage : p.coverageAmount || 0).toLocaleString("en-IN")}`,
    `INR ${(p.premiumAmount || 0).toLocaleString("en-IN")}`,
    p.startDate ? new Date(p.startDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A',
    p.policyStatus || "PENDING"
  ]);

  autoTable(doc, {
    startY: 65,
    head: tableHeaders,
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [26, 60, 94],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9
    },
    styles: {
      fontSize: 8,
      cellPadding: 3
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 26 },
      1: { fontStyle: "bold" },
      8: { fontStyle: "bold" }
    },
    didDrawCell: (data) => {
      if (data.column.index === 8 && data.cell.section === "body") {
        const text = data.cell.text[0];
        const isActive = text === "ACTIVE";
        doc.setFillColor(data.row.index % 2 === 0 ? 255 : 245, 245, 245);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 3, data.cell.y + 4, text, isActive);
      }
    }
  });

  drawFooter(doc, 1);
  doc.save(`policy_registry_report.pdf`);
};

// 8. Generate Bulk Customers List PDF
export const generateCustomerListPDF = (customers) => {
  const doc = new jsPDF();
  drawHeader(doc, "Customer Registry Directory");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(26, 60, 94);
  doc.text("System Customer Directory Summary", 15, 52);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total Records Extracted: ${customers.length}`, 15, 58);

  const tableHeaders = [["ID", "Full Name", "Email Address", "Phone Number", "DOB", "Location", "Nominee"]];
  const tableData = customers.map(c => [
    String(c.id || "N/A"),
    c.fullName || "N/A",
    c.email || "N/A",
    c.phoneNumber || "N/A",
    c.dateOfBirth ? new Date(c.dateOfBirth).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A',
    c.city && c.state ? `${c.city}, ${c.state}` : c.city || c.state || 'N/A',
    c.nomineeName ? `${c.nomineeName} (${c.nomineeRelation || 'Nominee'})` : 'N/A'
  ]);

  autoTable(doc, {
    startY: 65,
    head: tableHeaders,
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [26, 60, 94],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9
    },
    styles: {
      fontSize: 8,
      cellPadding: 3
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { fontStyle: "bold" }
    }
  });

  drawFooter(doc, 1);
  doc.save(`customer_registry_report.pdf`);
};

// 9. Generate Bulk Claims List PDF
export const generateClaimListPDF = (claims) => {
  const doc = new jsPDF();
  drawHeader(doc, "Claims Registry Directory");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(26, 60, 94);
  doc.text("System Claims Directory Summary", 15, 52);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total Records Extracted: ${claims.length}`, 15, 58);

  const tableHeaders = [["Claim No.", "Policy ID/No.", "Incident Date", "Reason", "Amount", "Status", "Agent Remarks", "Admin Remarks"]];
  const tableData = claims.map(c => [
    c.claimNumber || `CLM-${c.id}`,
    c.policyNumber || "N/A",
    c.incidentDate || "N/A",
    c.claimReason || "N/A",
    `INR ${(c.claimAmount || 0).toLocaleString("en-IN")}`,
    c.claimStatus || "SUBMITTED",
    c.agentRemarks === "null" || !c.agentRemarks ? "Pending" : c.agentRemarks,
    c.adminRemarks === "null" || !c.adminRemarks ? "Pending" : c.adminRemarks
  ]);

  autoTable(doc, {
    startY: 65,
    head: tableHeaders,
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [26, 60, 94],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9
    },
    styles: {
      fontSize: 8,
      cellPadding: 3
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 25 },
      1: { fontStyle: "bold", cellWidth: 20 },
      5: { fontStyle: "bold", cellWidth: 25 }
    },
    didDrawCell: (data) => {
      if (data.column.index === 5 && data.cell.section === "body") {
        const text = data.cell.text[0];
        const statusLower = text.toLowerCase();
        const isApproved = statusLower === "approved" || statusLower === "recommended" || statusLower === "success" || statusLower === "active";
        doc.setFillColor(data.row.index % 2 === 0 ? 255 : 245, 245, 245);
        doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
        drawStatusBadge(doc, data.cell.x + 3, data.cell.y + 4, text, isApproved);
      }
    }
  });

  drawFooter(doc, 1);
  doc.save(`claims_registry_report.pdf`);
};

